// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDygpqEsXAcT1s8VAMtG_cUbs8Vxybo3Ao',
    appId: '1:101982381996:web:a1774f29b17ce8682b3c09',
    messagingSenderId: '101982381996',
    projectId: 'shokuhi-52960',
    authDomain: 'shokuhi-52960.firebaseapp.com',
    storageBucket: 'shokuhi-52960.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjkTSpobIVGox5E7W9kXEawJipBVX82RU',
    appId: '1:101982381996:android:e93e4b8fefa656e22b3c09',
    messagingSenderId: '101982381996',
    projectId: 'shokuhi-52960',
    storageBucket: 'shokuhi-52960.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLqaWI8jKGgYUsIItqi4-Rz9yGpx9Aiss',
    appId: '1:101982381996:ios:ee7ea795d7f76de82b3c09',
    messagingSenderId: '101982381996',
    projectId: 'shokuhi-52960',
    storageBucket: 'shokuhi-52960.appspot.com',
    iosClientId: '101982381996-0ufp6hvipju3v7bqo59ij2juqkgk7kiu.apps.googleusercontent.com',
    iosBundleId: 'com.example.shokuhi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLqaWI8jKGgYUsIItqi4-Rz9yGpx9Aiss',
    appId: '1:101982381996:ios:ee7ea795d7f76de82b3c09',
    messagingSenderId: '101982381996',
    projectId: 'shokuhi-52960',
    storageBucket: 'shokuhi-52960.appspot.com',
    iosClientId: '101982381996-0ufp6hvipju3v7bqo59ij2juqkgk7kiu.apps.googleusercontent.com',
    iosBundleId: 'com.example.shokuhi',
  );
}
